Repository bcoin-org/bcoin, pull requests merged in 2019-04, with the labels that each got.

#741 npm scripts: delete webpack
  package.json
Labels: quick, ready for review

#736 Remove coin cache
  CHANGELOG.md
  browser/src/app.js
  docs/configuration.md
  etc/sample.conf
  lib/blockchain/chain.js
  lib/blockchain/chaindb.js
  lib/node/fullnode.js
Labels: ready for review, stability / efficiency

#730 test: document bech32 test vectors
  test/bech32-test.js
Labels: quick
