Repository bcoin-org/bcoin, pull requests merged in 2019-03, with the labels that each got.

#683 bench: update and fix api and dependencies
  bench/buffer.js
  bench/chacha.js
  bench/coins.js
  bench/merkle.js
  bench/tx.js
  bench/walletdb.js
Labels: quick

#702 Changelog updates
  CHANGELOG.md
Labels: docs

#705 rpc help list commands
  lib/node/rpc.js
  lib/wallet/rpc.js
Labels: quick

#557 Wallet option to skip templates.
  CHANGELOG.md
  lib/wallet/http.js
  lib/wallet/wallet.js
  test/http-test.js
  test/wallet-test.js
Labels: wallet

#550 RPC: fix several wallet RPC calls and add RPC tests
  lib/wallet/rpc.js
  lib/wallet/txdb.js
  lib/wallet/wallet.js
  lib/wallet/walletdb.js
  test/rpc-test.js
  test/util/assert.js
Labels: bug fix, tests, wallet
