Repository bcoin-org/bcoin, pull requests merged in 2019-10, with the labels that each got.

#743 bcoin: use cryptographic randomness
  lib/mining/miner.js
  lib/mining/template.js
  lib/net/common.js
  lib/net/hostlist.js
Labels: enhancement, quick

#870 node/http: get info mempool orphan count
  lib/node/http.js
Labels: api, quick

#876 Fix jsdocs for broadcast arguments
  lib/net/peer.js
  lib/net/pool.js
Labels: quick

#878 Add title to worker processes
  lib/workers/worker.js
Labels: quick

#890 bwallet-cli: add sign parameter
  bin/bwallet-cli
Labels: api, http, quick, ready for review, wallet

#891 wallet-rpc: dump wallet backup with correct network
  lib/wallet/rpc.js
Labels: api, bug, quick, rpc, wallet

#729 Quit if native bcrypto bindings are missing
  bin/node
  bin/spvnode
Labels: ready for review
